### PR TITLE
Add docs on staying up to date with changes

### LINKED ISSUE #339: Add guidance on staying up to date
## What

Replace the [existing guidance on updating with npm](https://frontend.design-system.service.gov.uk/updating-with-npm/) with new guidance that covers:

- the benefits of staying up to date
- how to find out what version you are currently using
- how to update if you've installed GOV.UK Frontend from precompiled files
- how to be notified when there's a new release (replacing [the existing guidance in the README](https://github.com/alphagov/govuk-frontend#getting-updates))
- how versioning works
- how to use the release notes effectively (for example what each of the sections mean)

Then:

- redirect the old path for the updating with npm guidance to the new docs
- replace the section in the README with a link to the docs
- add a link from the top of the changelog to the new guidance

## Why

We want to encourage all users – not just those who have installed from npm – to keep up to date with new releases.

We want to be able to link from the release notes to some supporting material that helps users understand how to use them effectively.

## Who needs to know about this

Tech writer, developers

## Done when

- [ ] New guidance on staying up to date has been published
- [ ] README updated to remove duplication and link to the new guidance
- [x] The existing URL for the updating with npm guidance redirects to the new guidance

### PR DESCRIPTION
**Pull request by 36degrees**
This doc replaces the ‘Updating with npm’ guidance and the ‘Getting updates’ section in GOV.UK Frontend’s README.

We can then add a link to this guidance from the release notes to help users understand how to use the release notes effectively.

Closes #339.

### CODE REVIEW

**Review by owenatgov — APPROVED** [review]
Looks good to me!

**Comment by 36degrees** [comment]
@claireashworth has made some minor tweaks to the Google Doc version of this that need syncing up.

We're also trying to get the page 2i'ed as its' new.

I'll wait until the 2i happens before bringing the changes across – in the mean time I'll put this back in draft.

**Comment by 36degrees** [comment]
Updated with changes from 2i – @owenatgov are you able to take another look to check you're happy?

**Comment by 36degrees** [comment]
Rebased on top of #343.

**Review by owenatgov — APPROVED** [review]
Double approved

**Pull request merged**
