### PR TITLE
Preview v5: Archive the announcement page

### PR DESCRIPTION
**Pull request by stevenjmesser**
Archives the v5 announcement - no longer needed now that we have merged the docs.

### CODE REVIEW

**Review by colinrotherham — DISMISSED** [review]
Approved to merge into the `release/5.0` preview branch 🎉

**Comment by colinrotherham** [comment]
@stevenjmesser Not sure if we need to archive this page, rather than delete it

Related https://github.com/alphagov/govuk-frontend-docs/pull/332#issuecomment-1663762645 regarding legacy pages being removed versus the [**Archiving deleted URLs**](https://github.com/alphagov/govuk-design-system/blob/main/docs/contributing/archiving-deleted-urls.md) guidance

Different repo, but same principle

**Comment by colinrotherham** [comment]
I've updated the PR to archive the page instead

**Comment by stevenjmesser** [comment]
Thanks @colinrotherham, looks good to me. Needs an approving review from someone else as I was the contributor.

**Comment by colinrotherham** [comment]
@stevenjmesser Well I did the archiving, so perhaps @claireashworth please?

I've assumed linking to the "Changes in v5" page would be the best place post-release

**Review by claireashworth — APPROVED** [review]

**Pull request merged**
